### ISSUE TITLE
mms_python_client is missing

### ISSUE THREAD

**Issue by thSoft** [IncQueryLabs/incquery-server-jupyter#19]
When performing a local installation as described in the readme with pip3.7, the mms_python_client dependency is still missing. (Where should this dependency be declared?)

**Comment by bergmanngabor** [comment]
It is a public package available from both [conda-forge](https://anaconda.org/conda-forge/mms-python-client) and [PyPI](https://pypi.org/project/mms-python-client/). 

The "[Additional dependencies](https://github.com/IncQueryLabs/incquery-server-jupyter#additional-dependencies)" section in the readme should be updated so that the user understands that this needs to be set up along with the plotting libraries.
