### ISSUE TITLE
Implement OIDC based authentication

### ISSUE THREAD

**Issue by FuzesiMate** [IncQueryLabs/incquery-server-jupyter#46]
OIDC (Api token) based authentication is implemented in the raw Python client as an extension
- [ ] Use the extension in iqs jupyter to enable OIDC based authentication

**Comment by bergmanngabor** [comment]
Since the client needs to indicate whether they connect to an OIDC-capable server or not, the `connect()` function and the IQS connector widget must both be extended with a new bool parameter / checkbox. The default value shall be possible to provide via envvar, see https://github.com/IncQueryLabs/incquery-server-jupyter/blob/master/source/incqueryserver-jupyter/iqs_jupyter/config_defaults.py.

@FuzesiMate am I correct in assuming that there has been no progress along this direction?
